### ISSUE TITLE
Realtime pose estimation

### ISSUE THREAD

**Issue by Zumbalamambo** [HYPJUDY/human-pose-estimation-by-deep-learning#1]
How do I estimate pose realtime?

**Comment by HYPJUDY** [comment]
This project may not support realtime estimation, but I refer you to [Realtime Multi-Person Pose Estimation](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) project by Zhe Cao et al. Thanks : )

**Comment by HYPJUDY** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
