### ISSUE TITLE
Error when training with RGB images

### ISSUE THREAD

**Issue by ML-DL-AI-SS** [HYPJUDY/human-pose-estimation-by-deep-learning#10]
Hi!
I'm getting this error when trying to train the model with rgb images.

```
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    main()
  File "train.py", line 118, in main
    imgs, fm, coords, begins, filename_list = reader.get_random_batch(distort=config.toDistort)
read_data.py", line 310, in get_random_batch
    return (imgs.reshape([self.batch_size, self.img_height, self.img_width, 1]),
ValueError: cannot reshape array of size 60120000 into shape (20,1002,1000,1)
```
can anyone help me out with this issue?

Thanks in advance!!

**Comment by HYPJUDY** [comment]
RGB images has three channels in the last dimension, so modify the code to
`return (imgs.reshape([self.batch_size, self.img_height, self.img_width, 3])`
would solve this error.

**Comment by ML-DL-AI-SS** [comment]
Thanks a lot for your response. I tried doing that but getting the same error.

**Comment by HYPJUDY** [comment]
You mean you got the error of `ValueError: cannot reshape array of size 60120000 into shape (20,1002,1000,3)`? It's unreasonable since `60120000 = 20*1002*1000*3`.

**Comment by ML-DL-AI-SS** [comment]
Sorry the error is 
`ValueError: Cannot feed value of shape (20, 1002, 1000, 3) for Tensor u'Placeholder:0', which has shape '(20, 1002, 1000, 1)'`

I have changed the following lines in read_data.py 

line 69:  img = cv2.resize(img, (self.img_width, self.img_height),3)
line 104: img = cv2.resize(img, (self.img_width, self.img_height),3)
line 310: return (imgs.reshape([self.batch_size, self.img_height, self.img_width, 3]),
line 325: return (imgs.reshape([self.batch_size, self.img_height, self.img_width, 3]),
and in cpm.py :
line 28: shape = (self.batch_size, config.img_height, config.img_width, 3)

I could rectify the previous error but then I'm getting the following error:
```
cpm.py", line 207, in conv_layer
    conv = tf.nn.conv2d(bottom, kernel, [1, 1, 1, 1], padding="SAME")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
```

**Comment by ML-DL-AI-SS** [comment]
The error was due to the large size of the input files. could resolve it by resizing the images.
