### ISSUE TITLE
What is the format of the annos files?

### ISSUE THREAD

**Issue by AviP1234** [HYPJUDY/human-pose-estimation-by-deep-learning#2]
What are the joints corresponding to labels and the order of their x,y in the file?
Moreover, do the code can cope with partial labels? I.e not all joints are known or visible in every training image? 
Thank you

**Comment by HYPJUDY** [comment]
I have updated the [README file](https://github.com/HYPJUDY/human-pose-estimation-by-deep-learning/blob/master/README.md#utils) and draw_point.py to answer your question. Please see the update or run draw_point.py for more details. Thanks a lot!

**Comment by AviP1234** [comment]
Thank you,
So the code can't cope with partial labels?  
And one more question:
Why do you read the least labels separately?
(begin in records and later begins_list)

**Comment by HYPJUDY** [comment]
The code can't cope with inconsistent labels (e.g. one image is labeled with 14 joints while others are labeled with 15 joints) but can cope with partial labels if all trained images are labeled by the same method (e.g. all images are labeled with x points in the same order, x can be bigger or smaller than 15). Btw, if you want to delete some labeled points based on my annos files, you can refer to [delete_points_by_position.py](https://github.com/HYPJUDY/human-pose-estimation-by-deep-learning/blob/master/labels/python/delete_points_by_position.py).

As for the other question, I am not sure what's "the least labels". If what you mean is the '1' at the end of each line of annos file, then to my knowledge, the '1's are useless. They are stacked and returned (`out_begins = np.stack(begins_list)`) as `begins` but not further used (e.g. see from [L118 in train.py](https://github.com/HYPJUDY/human-pose-estimation-by-deep-learning/blob/f2178d164ba43104c106a69ce96c3659d01e7699/train.py#L118)). Sorry to have confused you for this useless '1'.

**Comment by AviP1234** [comment]
thank you

**Comment by HYPJUDY** [comment]
You are welcome. Closing this. Please feel free to reopen it if you meet any further problem.
