### ISSUE TITLE
What dataset used for training and testing?

### ISSUE THREAD

**Issue by zhezh** [HYPJUDY/human-pose-estimation-by-deep-learning#3]
I saw you write:

> Please contact with JakeRenn for data (maybe not available currently). 

And then I go to JakeRenn's project, there is no update.

I wonder what dataset is used in your project for training? Is it MPII as Wei's paper referred?

**Comment by HYPJUDY** [comment]
Hi, the dataset used in this code is labeled and cleaned by JakeRenn's team, which is different from MPII. This dataset is small and simple as I have described and showed some [demo images](https://github.com/HYPJUDY/human-pose-estimation-by-deep-learning/tree/master/data/input).
> human-pose-estimation-by-deep-learning/data/input/test_imgs: ~4000 test images
human-pose-estimation-by-deep-learning/data/input/train_imgs: ~60000 train images, use half of them. Each of them are labeled with 15 articulate points.

It's up to them to decide whether to release the dataset. If this dataset is not available currently, I recommend you to use other human pose dataset like MPII which may be better than us.
Thanks.

**Comment by zhezh** [comment]
Thanks for your kind reply~

**Comment by HYPJUDY** [comment]
You are welcome. Closing this. Please feel free to reopen it if you meet any further problem.
