### ISSUE TITLE
The original dataset has the formatof .mat,but I have on idea of how to transform it to this porject

### ISSUE THREAD

**Issue by Bigwode** [HYPJUDY/human-pose-estimation-by-deep-learning#5]
The original dataset has the format of .mat, but I have on idea of how to transform it to suit this porject. So can you share your training-set ?Thanks a lot !

**Comment by HYPJUDY** [comment]
Hi @Bigwode , since the data is from [JakeRenn](https://github.com/JakeRenn/pose_estimation). Please contact with him for data (maybe not available currently).
