### ISSUE TITLE
Real-Time Estimation

### ISSUE THREAD

**Issue by oguzhankarabulut** [HYPJUDY/human-pose-estimation-by-deep-learning#6]
It is really amazing project! Thanks for sharing!

I want to ask, is it good for real time pose estimations?

**Comment by HYPJUDY** [comment]
Thank you! Please refer to #1 that
This project may not support realtime estimation, but I refer you to [Realtime Multi-Person Pose Estimation](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation) project by Zhe Cao et al. Thanks : )
Closing this. Please feel free to reopen it if you meet any further problem.
